name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Build Docker image
        run: |
         docker build -t sanjay .

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 225989371791.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Tag Docker image
        run: |
          docker tag sanjay:latest 225989371791.dkr.ecr.us-east-1.amazonaws.com/sanjay:latest
      - name: Push Docker image to ECR
        run: |
          docker push 225989371791.dkr.ecr.us-east-1.amazonaws.com/sanjay:latest
